name: aluco
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_icons: ^0.3.1
  datetime_picker_formfield: ^0.4.3
  bloc_provider: ^0.6.2+2
  intl: ^0.15.8
  image_picker: ^0.6.1+8
  gender_selector: ^1.0.6
  dio: ^3.0.3
  rxdart: ^0.22.4
  ndialog: ^2.0.2
  connectivity: ^0.4.5+1
  flutter_spinkit: ^4.0.0
  shared_preferences: ^0.5.4
  gg_flutter_components:
    git:
      url: git://github.com/rodrigobastosv/gg_flutter_components.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
