name: aluco
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_icons: ^0.3.1
  image_picker: ^0.6.1+8
  dio: ^3.0.3
  connectivity: ^0.4.5+1
  flutter_spinkit: ^4.0.0
  shared_preferences: ^0.5.4
  gg_flutter_components:
    git:
      url: git://github.com/rodrigobastosv/gg_flutter_components.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
