name: aluco
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_icons: ^0.3.1
  datetime_picker_formfield: ^0.4.3
  bloc_pattern: ^2.3.2
  intl: ^0.15.8
  alice: ^0.0.17
  numberpicker: ^1.1.0
  toggle_switch: ^0.1.4
  image_picker: ^0.6.1+8
  gender_selector: ^1.0.6
  dio: 3.0.3
  flutter_sujian_select: ^1.0.1
  mask_text_input_formatter: ^1.0.5
  rxdart: ^0.22.4
  connectivity: ^0.4.5+1
  circular_check_box: ^1.0.1
  table_calendar: ^2.2.1
  line_icons: ^0.2.0
  shared_preferences: ^0.5.4
  flutter_masked_text: ^0.8.0
  introduction_screen: ^1.0.7
  connectivity_alert_widget: ^1.0.0
  gg_flutter_components:
    git:
      url: git://github.com/rodrigobastosv/gg_flutter_components.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.15.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: OleoScriptSwashCaps
      fonts:
        - asset: assets/fonts/OleoScriptSwashCaps/OleoScriptSwashCaps-Regular.ttf
        - asset: assets/fonts/OleoScriptSwashCaps/OleoScriptSwashCaps-Bold.ttf
          weight: 700
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700
