name: aluco
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core
  get_it: ^3.0.3
  bloc_pattern: ^2.3.2
  intl: ^0.15.8
  alice: ^0.0.17
  dio: 3.0.3
  rxdart: ^0.22.4
  shared_preferences: ^0.5.4
  catcher: ^0.2.7
  flutter_local_notifications: ^0.8.4+3
  get: ^1.6.3

  # UI
  cupertino_icons: ^0.1.2
  fancy_shimmer_image: ^1.0.0
  tutorial_coach_mark: ^0.3.0
  flutter_icons: ^0.3.1
  datetime_picker_formfield: ^0.4.3
  toggle_switch: ^0.1.4
  image_picker: ^0.6.1+8
  flutter_sujian_select: ^1.0.1
  circular_check_box: ^1.0.1
  table_calendar: ^2.2.1
  line_icons: ^0.2.0
  flutter_masked_text: ^0.8.0
  introduction_screen: ^1.0.7
  connectivity_alert_widget: ^1.0.0
  ndialog: ^2.0.2+1
  gg_flutter_components:
    git:
      url: git://github.com/rodrigobastosv/gg_flutter_components.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3
  flutter_native_splash: ^0.1.9

dependency_overrides:
  intl: ^0.15.8

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/launcher_foreground.png"
  adaptive_icon_background: "assets/images/launcher_background.png"
  adaptive_icon_foreground: "assets/images/launcher_foreground.png"

flutter_native_splash:
  image: assets/images/splash_foreground.png
  color: "fb8c00"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: OleoScriptSwashCaps
      fonts:
        - asset: assets/fonts/OleoScriptSwashCaps/OleoScriptSwashCaps-Regular.ttf
        - asset: assets/fonts/OleoScriptSwashCaps/OleoScriptSwashCaps-Bold.ttf
          weight: 700
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700
